package main

import "github.com/newrelic/infra-integrations-sdk/metric"

var commonDefinition = map[string][]interface{}{
	"software.version":   {"org.apache.cassandra.db:type=StorageService,attr=ReleaseVersion", metric.ATTRIBUTE},
	"cluster.name":       {"org.apache.cassandra.db:type=StorageService,attr=ClusterName", metric.ATTRIBUTE},
	"cluster.datacenter": {"org.apache.cassandra.db:type=EndpointSnitchInfo,attr=Datacenter", metric.ATTRIBUTE},
	"cluster.rack":       {"org.apache.cassandra.db:type=EndpointSnitchInfo,attr=Rack", metric.ATTRIBUTE},
}

// All metrics we want to provide for the cassandra integration
var metricsDefinition = map[string][]interface{}{
	"provider.viewWriteLatencyPerSecond":   {"org.apache.cassandra.metrics:type=ClientRequest,scope=ViewWrite,name=Latency,attr=OneMinuteRate", metric.GAUGE},
	"provider.rangeSliceLatencyPerSecond":  {"org.apache.cassandra.metrics:type=ClientRequest,scope=RangeSlice,name=Latency,attr=OneMinuteRate", metric.GAUGE},
	"provider.CASWriteLatencyPerSecond":    {"org.apache.cassandra.metrics:type=ClientRequest,scope=CASWrite,name=Latency,attr=OneMinuteRate", metric.GAUGE},
	"provider.readLatencyPerSecond":        {"org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Latency,attr=OneMinuteRate", metric.GAUGE},
	"provider.CASReadLatencyPerSecond":     {"org.apache.cassandra.metrics:type=ClientRequest,scope=CASRead,name=Latency,attr=OneMinuteRate", metric.GAUGE},
	"provider.writeLatencyPerSecond":       {"org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Latency,attr=OneMinuteRate", metric.GAUGE},
	"provider.writeLatency98thPercentile":  {"org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Latency,attr=98thPercentile", metric.GAUGE},
	"provider.writeLatency99thPercentile":  {"org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Latency,attr=99thPercentile", metric.GAUGE},
	"provider.writeLatency999thPercentile": {"org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Latency,attr=999thPercentile", metric.GAUGE},
	"provider.writeLatency50thPercentile":  {"org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Latency,attr=50thPercentile", metric.GAUGE},
	"provider.writeLatency75thPercentile":  {"org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Latency,attr=75thPercentile", metric.GAUGE},
	"provider.writeLatency95thPercentile":  {"org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Latency,attr=95thPercentile", metric.GAUGE},
	"provider.readLatency98thPercentile":   {"org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Latency,attr=98thPercentile", metric.GAUGE},
	"provider.readLatency99thPercentile":   {"org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Latency,attr=99thPercentile", metric.GAUGE},
	"provider.readLatency999thPercentile":  {"org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Latency,attr=999thPercentile", metric.GAUGE},
	"provider.readLatency50thPercentile":   {"org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Latency,attr=50thPercentile", metric.GAUGE},
	"provider.readLatency75thPercentile":   {"org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Latency,attr=75thPercentile", metric.GAUGE},
	"provider.readLatency95thPercentile":   {"org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Latency,attr=95thPercentile", metric.GAUGE},

	"provider.readTimeoutsPerSecond":          {"org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Timeouts,attr=OneMinuteRate", metric.GAUGE},
	"provider.readUnavailablesPerSecond":      {"org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Unavailables,attr=OneMinuteRate", metric.GAUGE},
	"provider.writeTimeoutsPerSecond":         {"org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Timeouts,attr=OneMinuteRate", metric.COUNTER},
	"provider.writeUnavailablesPerSecond":     {"org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Unavailables,attr=OneMinuteRate", metric.GAUGE},
	"provider.rangeSliceTimeoutsPerSecond":    {"org.apache.cassandra.metrics:type=ClientRequest,scope=RangeSlice,name=Timeouts,attr=OneMinuteRate", metric.GAUGE},
	"provider.rangeSliceUnavalablesPerSecond": {"org.apache.cassandra.metrics:type=ClientRequest,scope=RangeSlice,name=Unavailables,attr=OneMinuteRate", metric.GAUGE},

	"provider.requestCounterMutationStageActiveTasks":       {"org.apache.cassandra.metrics:type=ThreadPools,path=request,scope=CounterMutationStage,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.requestCounterMutationStagePendingTasks":      {"org.apache.cassandra.metrics:type=ThreadPools,path=request,scope=CounterMutationStage,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.requestMutationStageActiveTasks":              {"org.apache.cassandra.metrics:type=ThreadPools,path=request,scope=MutationStage,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.requestMutationStagePendingTasks":             {"org.apache.cassandra.metrics:type=ThreadPools,path=request,scope=MutationStage,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.requestReadRepairStageActiveTasks":            {"org.apache.cassandra.metrics:type=ThreadPools,path=request,scope=ReadRepairStage,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.requestReadRepairStagePendingTasks":           {"org.apache.cassandra.metrics:type=ThreadPools,path=request,scope=ReadRepairStage,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.requestReadStageActiveTasks":                  {"org.apache.cassandra.metrics:type=ThreadPools,path=request,scope=ReadStage,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.requestReadStagePendingTasks":                 {"org.apache.cassandra.metrics:type=ThreadPools,path=request,scope=ReadStage,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.requestRequestResponseStageActiveTasks":       {"org.apache.cassandra.metrics:type=ThreadPools,path=request,scope=RequestResponseStage,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.requestRequestResponseStagePendingTasks":      {"org.apache.cassandra.metrics:type=ThreadPools,path=request,scope=RequestResponseStage,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.requestViewMutationStageActiveTasks":          {"org.apache.cassandra.metrics:type=ThreadPools,path=request,scope=ViewMutationStage,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.requestViewMutationStagePendingTasks":         {"org.apache.cassandra.metrics:type=ThreadPools,path=request,scope=ViewMutationStage,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.internalAntiEntropyStageActiveTasks":          {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=AntiEntropyStage,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.internalAntiEntropyStagePendingTasks":         {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=AntiEntropyStage,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.internalCacheCleanupExecutorActiveTasks":      {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=CacheCleanupExecutor,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.internalCacheCleanupExecutorPendingTasks":     {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=CacheCleanupExecutor,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.internalCompactionExecutorActiveTasks":        {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=CompactionExecutor,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.internalCompactionExecutorPendingTasks":       {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=CompactionExecutor,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.internalGossipStageActiveTasks":               {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=GossipStage,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.internalGossipStagePendingTasks":              {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=GossipStage,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.internalHintsDispatcherActiveTasks":           {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=HintsDispatcher,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.internalHintsDispatcherPendingTasks":          {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=HintsDispatcher,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.internalInternalResponseStageActiveTasks":     {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=InternalResponseStage,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.internalInternalResponseStagePendingTasks":    {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=InternalResponseStage,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.internalMemtableFlushWriterActiveTasks":       {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=MemtableFlushWriter,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.internalMemtableFlushWriterPendingTasks":      {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=MemtableFlushWriter,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.internalMemtablePostFlushActiveTasks":         {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=MemtablePostFlush,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.internalMemtablePostFlushPendingTasks":        {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=MemtablePostFlush,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.internalMemtableReclaimMemoryActiveTasks":     {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=MemtableReclaimMemory,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.internalMemtableReclaimMemoryPendingTasks":    {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=MemtableReclaimMemory,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.internalMigrationStageActiveTasks":            {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=MigrationStage,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.internalMigrationStagePendingTasks":           {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=MigrationStage,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.internalMiscStageActiveTasks":                 {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=MiscStage,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.internalMiscStagePendingTasks":                {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=MiscStage,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.internalPendingRangeCalculatorActiveTasks":    {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=PendingRangeCalculator,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.internalPendingRangeCalculatorPendingTasks":   {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=PendingRangeCalculator,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.internalSamplerActiveTasks":                   {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=Sampler,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.internalSamplerPendingTasks":                  {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=Sampler,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.internalSecondaryIndexManagementActiveTasks":  {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=SecondaryIndexManagement,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.internalSecondaryIndexManagementPendingTasks": {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=SecondaryIndexManagement,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.internalValidationExecutorActiveTasks":        {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=ValidationExecutor,name=ActiveTasks,attr=Value", metric.GAUGE},
	"provider.internalValidationExecutorPendingTasks":       {"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=ValidationExecutor,name=PendingTasks,attr=Value", metric.GAUGE},

	"provider.droppedBatchRemoveMessagesPerSecond":     {"org.apache.cassandra.metrics:type=DroppedMessage,scope=BATCH_REMOVE,name=Dropped,attr=Count", metric.COUNTER},
	"provider.droppedBatchStoreMessagesPerSecond":      {"org.apache.cassandra.metrics:type=DroppedMessage,scope=BATCH_STORE,name=Dropped,attr=Count", metric.COUNTER},
	"provider.droppedCounterMutationMessagesPerSecond": {"org.apache.cassandra.metrics:type=DroppedMessage,scope=COUNTER_MUTATION,name=Dropped,attr=Count", metric.COUNTER},
	"provider.droppedHintMessagesPerSecond":            {"org.apache.cassandra.metrics:type=DroppedMessage,scope=HINT,name=Dropped,attr=Count", metric.COUNTER},
	"provider.droppedMutationMessagesPerSecond":        {"org.apache.cassandra.metrics:type=DroppedMessage,scope=MUTATION,name=Dropped,attr=Count", metric.COUNTER},
	"provider.droppedPagedRangeMessagesPerSecond":      {"org.apache.cassandra.metrics:type=DroppedMessage,scope=PAGED_RANGE,name=Dropped,attr=Count", metric.COUNTER},
	"provider.droppedRangeSliceMessagesPerSecond":      {"org.apache.cassandra.metrics:type=DroppedMessage,scope=RANGE_SLICE,name=Dropped,attr=Count", metric.COUNTER},
	"provider.droppedReadMessagesPerSecond":            {"org.apache.cassandra.metrics:type=DroppedMessage,scope=READ,name=Dropped,attr=Count", metric.COUNTER},
	"provider.droppedReadRepairMessagesPerSecond":      {"org.apache.cassandra.metrics:type=DroppedMessage,scope=READ_REPAIR,name=Dropped,attr=Count", metric.COUNTER},
	"provider.droppedRequestResponseMessagesPerSecond": {"org.apache.cassandra.metrics:type=DroppedMessage,scope=REQUEST_RESPONSE,name=Dropped,attr=Count", metric.COUNTER},
	"provider.droppedTraceMessagesPerSecond":           {"org.apache.cassandra.metrics:type=DroppedMessage,scope=_TRACE,name=Dropped,attr=Count", metric.COUNTER},

	"provider.liveSSTableCount":         {"org.apache.cassandra.metrics:type=ColumnFamily,name=LiveSSTableCount,attr=Value", metric.GAUGE},
	"provider.onHeapMemtablesDataSize":  {"org.apache.cassandra.metrics:type=ColumnFamily,name=AllMemtablesHeapSize,attr=Value", metric.GAUGE},
	"provider.offHeapMemtablesDataSize": {"org.apache.cassandra.metrics:type=ColumnFamily,name=AllMemtablesOffHeapSize,attr=Value", metric.GAUGE},

	"provider.totalHintsPerSecond":  {"org.apache.cassandra.metrics:type=Storage,name=TotalHints,attr=Count", metric.COUNTER},
	"provider.totalHintsInProgress": {"org.apache.cassandra.metrics:type=Storage,name=TotalHintsInProgress,attr=Count", metric.GAUGE},

	"provider.keyCacheCapacityInBytes":   {"org.apache.cassandra.metrics:type=Cache,scope=KeyCache,name=Capacity,attr=Value", metric.GAUGE},
	"provider.keyCacheHitsPerSecond":     {"org.apache.cassandra.metrics:type=Cache,scope=KeyCache,name=Hits,attr=OneMinuteRate", metric.GAUGE},
	"provider.keyCacheHitRatio":          {"org.apache.cassandra.metrics:type=Cache,scope=KeyCache,name=HitRate,attr=Value", metric.GAUGE},
	"provider.keyCacheRequestsPerSecond": {"org.apache.cassandra.metrics:type=Cache,scope=KeyCache,name=Requests,attr=OneMinuteRate", metric.GAUGE},
	"provider.keyCacheSize":              {"org.apache.cassandra.metrics:type=Cache,scope=KeyCache,name=Size,attr=Value", metric.GAUGE},
	"provider.rowCacheCapacityInBytes":   {"org.apache.cassandra.metrics:type=Cache,scope=RowCache,name=Capacity,attr=Value", metric.GAUGE},
	"provider.rowCacheHitsPerSecond":     {"org.apache.cassandra.metrics:type=Cache,scope=RowCache,name=Hits,attr=OneMinuteRate", metric.GAUGE},
	"provider.rowCacheHitRatio":          {"org.apache.cassandra.metrics:type=Cache,scope=RowCache,name=HitRate,attr=Value", metric.GAUGE},
	"provider.rowCacheRequestsPerSecond": {"org.apache.cassandra.metrics:type=Cache,scope=RowCache,name=Requests,attr=OneMinuteRate", metric.GAUGE},
	"provider.rowCacheSize":              {"org.apache.cassandra.metrics:type=Cache,scope=RowCache,name=Size,attr=Value", metric.GAUGE},

	"provider.commitLogCompletedTasksPerSecond": {"org.apache.cassandra.metrics:type=CommitLog,name=CompletedTasks,attr=Value", metric.COUNTER},
	"provider.commitLogPendindTasks":            {"org.apache.cassandra.metrics:type=CommitLog,name=PendingTasks,attr=Value", metric.GAUGE},
	"provider.commitLogTotalSize":               {"org.apache.cassandra.metrics:type=CommitLog,name=TotalCommitLogSize,attr=Value", metric.GAUGE},
}

var keyspaceDefinition = map[string][]interface{}{
	"provider.liveSSTableCount":               {"org.apache.cassandra.metrics:type=ColumnFamily,name=LiveSSTableCount,attr=Value", metric.GAUGE},
	"provider.pendingCompactions":             {"org.apache.cassandra.metrics:type=ColumnFamily,name=PendingCompactions,attr=Value", metric.GAUGE},
	"provider.liveDiskSpaceUsed":              {"org.apache.cassandra.metrics:type=ColumnFamily,name=LiveDiskSpaceUsed,attr=Count", metric.GAUGE},
	"provider.SSTAblesPerRead50thPercentile":  {"org.apache.cassandra.metrics:type=ColumnFamily,name=SSTablesPerReadHistogram,attr=50thPercentile", metric.GAUGE},
	"provider.SSTAblesPerRead75thPercentile":  {"org.apache.cassandra.metrics:type=ColumnFamily,name=SSTablesPerReadHistogram,attr=75thPercentile", metric.GAUGE},
	"provider.SSTAblesPerRead95thPercentile":  {"org.apache.cassandra.metrics:type=ColumnFamily,name=SSTablesPerReadHistogram,attr=95thPercentile", metric.GAUGE},
	"provider.SSTAblesPerRead98thPercentile":  {"org.apache.cassandra.metrics:type=ColumnFamily,name=SSTablesPerReadHistogram,attr=98thPercentile", metric.GAUGE},
	"provider.SSTAblesPerRead99thPercentile":  {"org.apache.cassandra.metrics:type=ColumnFamily,name=SSTablesPerReadHistogram,attr=99thPercentile", metric.GAUGE},
	"provider.SSTAblesPerRead999thPercentile": {"org.apache.cassandra.metrics:type=ColumnFamily,name=SSTablesPerReadHistogram,attr=999thPercentile", metric.GAUGE},
	"provider.writeLatencyPerSecond":          {"org.apache.cassandra.metrics:type=ColumnFamily,name=WriteLatency,attr=OneMinuteRate", metric.GAUGE},
	"provider.writeLatency50thPercentile":     {"org.apache.cassandra.metrics:type=ColumnFamily,name=WriteLatency,attr=50thPercentile", metric.GAUGE},
	"provider.writeLatency75thPercentile":     {"org.apache.cassandra.metrics:type=ColumnFamily,name=WriteLatency,attr=75thPercentile", metric.GAUGE},
	"provider.writeLatency95thPercentile":     {"org.apache.cassandra.metrics:type=ColumnFamily,name=WriteLatency,attr=95thPercentile", metric.GAUGE},
	"provider.writeLatency98thPercentile":     {"org.apache.cassandra.metrics:type=ColumnFamily,name=WriteLatency,attr=98thPercentile", metric.GAUGE},
	"provider.writeLatency99thPercentile":     {"org.apache.cassandra.metrics:type=ColumnFamily,name=WriteLatency,attr=99thPercentile", metric.GAUGE},
	"provider.writeLatency999thPercentile":    {"org.apache.cassandra.metrics:type=ColumnFamily,name=WriteLatency,attr=999thPercentile", metric.GAUGE},
	"provider.readLatencyPerSecond":           {"org.apache.cassandra.metrics:type=ColumnFamily,name=ReadLatency,attr=OneMinuteRate", metric.GAUGE},
	"provider.readLatency50thPercentile":      {"org.apache.cassandra.metrics:type=ColumnFamily,name=ReadLatency,attr=50thPercentile", metric.GAUGE},
	"provider.readLatency75thPercentile":      {"org.apache.cassandra.metrics:type=ColumnFamily,name=ReadLatency,attr=75thPercentile", metric.GAUGE},
	"provider.readLatency95thPercentile":      {"org.apache.cassandra.metrics:type=ColumnFamily,name=ReadLatency,attr=95thPercentile", metric.GAUGE},
	"provider.readLatency98thPercentile":      {"org.apache.cassandra.metrics:type=ColumnFamily,name=ReadLatency,attr=98thPercentile", metric.GAUGE},
	"provider.readLatency99thPercentile":      {"org.apache.cassandra.metrics:type=ColumnFamily,name=ReadLatency,attr=99thPercentile", metric.GAUGE},
	"provider.readLatency999thPercentile":     {"org.apache.cassandra.metrics:type=ColumnFamily,name=ReadLatency,attr=999thPercentile", metric.GAUGE},
	"provider.onHeapMemtablesDataSize":        {"org.apache.cassandra.metrics:type=ColumnFamily,name=AllMemtablesHeapSize,attr=Value", metric.GAUGE},
	"provider.offHeapMemtablesDataSize":       {"org.apache.cassandra.metrics:type=ColumnFamily,name=AllMemtablesOffHeapSize,attr=Value", metric.GAUGE},

	"provider.keyspace":                {"keyspace", metric.ATTRIBUTE},
	"provider.columnFamily":            {"columnFamily", metric.ATTRIBUTE},
	"provider.keyspaceAndColumnFamily": {"keyspaceAndColumnFamily", metric.ATTRIBUTE},
}

// The patterns used to get all the beans needed for the metrics defined above
var jmxPatterns = []string{
	"org.apache.cassandra.metrics:type=ClientRequest,scope=*,name=Latency",
	"org.apache.cassandra.metrics:type=ClientRequest,scope=*,name=Timeouts",
	"org.apache.cassandra.metrics:type=ClientRequest,scope=*,name=Unavailables",
	"org.apache.cassandra.metrics:type=ColumnFamily,name=LiveSSTableCount",
	"org.apache.cassandra.metrics:type=ColumnFamily,name=AllMemtablesHeapSize",
	"org.apache.cassandra.metrics:type=ColumnFamily,name=AllMemtablesOffHeapSize",
	"org.apache.cassandra.metrics:type=ThreadPools,path=request,scope=*,name=ActiveTasks",
	"org.apache.cassandra.metrics:type=ThreadPools,path=request,scope=*,name=PendingTasks",
	"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=*,name=ActiveTasks",
	"org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=*,name=PendingTasks",
	"org.apache.cassandra.metrics:type=DroppedMessage,scope=*,name=Dropped",
	"org.apache.cassandra.metrics:type=Storage,name=TotalHints",
	"org.apache.cassandra.metrics:type=Storage,name=TotalHintsInProgress",
	"org.apache.cassandra.metrics:type=Cache,scope=*,name=*",
	"org.apache.cassandra.metrics:type=CommitLog,name=*",
	// Cluster and software information
	"org.apache.cassandra.db:type=StorageService",
	"org.apache.cassandra.db:type=EndpointSnitchInfo",
	// Keyspace metrics
	"org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=LiveSSTableCount",
	"org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=SSTablesPerReadHistogram",
	"org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=LiveDiskSpaceUsed",
	"org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=ReadLatency",
	"org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=WriteLatency",
	"org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=LiveSSTableCount",
	"org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=PendingCompactions",
	"org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=AllMemtablesHeapSize",
	"org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=AllMemtablesOffHeapSize",
}
